### ISSUE TITLE
Provide quantization for nano

### ISSUE THREAD

**Issue by zhentaocc** [intel-analytics/BigDL#3600]
### Description
Propose to integrate quantization methods into nano to reduce the model size and accelerate inference. [Neural Compressor](https://github.com/intel/neural-compressor) provides a set of methods to quantize a model to simplify the usage.  
### Why Neural Compressor?  
Neural Compressor has provided a auto-tuning module to automatically search tuning space for best quantization config. User don't have to understand quantization tricks and details to get a well-quantized model.
### Steps 

- [ ] Install neural compressor, add it to `setup.py`
- [ ] Provide a class `QuantizationINC(...)` 
- [ ] Implement post-training quantization
- [ ] Implement quantization-aware training

### Design of `trainer.quantize`
```python
class QuantizationINC(..):
     def __init__(self, *args, **override_args):
         # initialize a INC Quantization instance
         ...
    def __call__(self, 
                 model,
                 calib_dataloader,
                 val_dataloaders = None):
          ...
          return qmodel
```
Here we provide a default config as a template for users to use. It is hard to decide a optimal config for all models, so uses have to make proper changes to configuration for best quantization process.

----------------------------------------------
Update:
Will split into 3 or 4 PRs to resolve INC/NNCF Pytorch/Tensorflow respectively. 
1. Support pytorch quantization using INC.
2. Support tensorflow quantization using INC.
3. Support pytorch quantization using NNCF.
4. Support tensorflow quantization using NNCF.

**Comment by jason-dai** [comment]
1. What's needed in the yaml file?
2. How many parameters does the user need to customize?
3. Can we use a Python dictionary (instead of a yaml file) for the user to specify customized parameters (on top of the default parameters)?
4. Please describe `calib_dataloader`, `val_dataloaders` and `datamodule`
5. Please also look at https://github.com/openvinotoolkit/nncf; preferably we should have an abstraction layer on top of INC and NNCF (for both PyTorch and TF).

**Comment by zhentaocc** [comment]
### For 3
yes we can do that, and we must document all the keys for users.
### For 1,2
As shown below, it is a template config for INC to run on Nano. I removed a great portion from INC template since they are required by Nano so we don't need to assign these keys in yaml.  I'm providing 3 template config yaml files for users: 

- post_training_dynamic_quant.yaml
- post_training_static_quant.yaml
- quantization_aware_training.yaml

**For a basic user**, he or she can specify the `tuning`:

1. Just specified `accuracy_criterion` to tell what kind of model is needed, like `relative: 0.1` meaning 0.1 accuracy drop is tolerable.
2. Additionally specify `strategy`, `exit_policy`

**For an advanced user**, he or she can specify the `model_wise` and `op_wise` to have a more restricted tuning space to reduce time for finding a satisfying quantized model.

```yaml
version: 1.0                                          # optional. reserved for future use. if not specified, a supported version would be written back to user yaml.

model:                                                # mandatory. used to specify model specific information.
  name: default                                       # mandatory. the model name.
  framework: pytorch_fx                               # mandatory. supported values are tensorflow, pytorch, pytorch_fx, pytorch_ipex, onnxrt_integer, onnxrt_qlinear or mxnet; allow new framework backend extension.
                                                      # Only tested on pytorch_fx for now.
#  inputs: image_tensor                               # optional. inputs and outputs fields are only required in tensorflow.
#  outputs: num_detections,detection_boxes,detection_scores,detection_classes

device: cpu                                           # optional. options:[cpu, gpu]. Default: cpu.

quantization:                                         # optional. tuning constraints on model-wise for advance user to reduce tuning space.
  approach: post_training_static_quant                # optional. default value is post_training_static_quant.
#  recipes:                                           # optional. used to switch neural_compressor int8 receipts ON or OFF.
#    scale_propagation_max_pooling: True              # optional. default value is True.
#    scale_propagation_concat: True                   # optional. default value is True.
#    first_conv_or_matmul_quantization: True          # optional. default value is True.
  calibration:                                       # optional. used to specify calibration behavior of post-training-static-quant. other quantization approachs are not necessary.
    sampling_size: 1000, 2000                        # optional. default value is 100. used to set how many samples should be used in calibration.

#  model_wise:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
#    weight:
#      granularity: per_channel
#      scheme: asym
#      dtype: int8
#      algorithm: minmax
#    activation:
#      granularity: per_tensor
#      scheme: sym
#      dtype: int8
#      algorithm: minmax, kl

#  op_wise: {                                         # optional. tuning constraints on op-wise for advance user to reduce tuning space.
#         'conv1': {
#           'activation':  {'dtype': ['uint8', 'fp32'], 'algorithm': ['minmax', 'kl'], 'scheme':['sym']},
#           'weight': {'dtype': ['int8', 'fp32'], 'algorithm': ['minmax']}
#         },
#         'pool1': {
#           'activation': {'dtype': ['int8'], 'scheme': ['sym'], 'granularity': ['per_tensor'], 'algorithm': ['minmax', 'kl']},
#         },
#         'default_qconfig': {                       # optional. set default qconfig to fp32 for FX model
#           'activation':  {'dtype': ['fp32']},
#           'weight': {'dtype': ['fp32']}
#         }
#       }

tuning:
  strategy:
    name: bayesian                                      # optional. default value is basic. other values are bayesian, mse, sigopt.
#    sigopt_api_token: YOUR-ACCOUNT-API-TOKEN             # optional. Necessary if strategy name is sigopt.
#    sigopt_project_id: PROJECT-ID                    # optional. Necessary if strategy name is sigopt.
#    sigopt_experiment_name: nc-tune                # optional. default is nc-tune if strategy name is sigopt.
  accuracy_criterion:
    relative:  0.1                                  # optional. default value is relative, other value is absolute. this example allows relative accuracy loss: 1%.
    higher_is_better: True
  objective: performance                             # optional. objective with accuracy constraint guaranteed. default value is performance. other values are modelsize and footprint.

  exit_policy:
    timeout: 0                                       # optional. tuning timeout (seconds). default value is 0 which means early stop. combine with max_trials field to decide when to exit.
    max_trials: 1000                                  # optional. max tune times. default value is 100. combine with timeout field to decide when to exit.
    performance_only: False                          # optional. max tune times. default value is False which means only generate fully quantized model.
  random_seed: 9527                                  # optional. random seed for deterministic tuning.
  tensorboard: False                                  # optional. dump tensor distribution in evaluation phase for debug purpose. default value is False.

  workspace:
    path: /path/to/saving/directory                  # optional. default workspace is ./nc_workspace/current_time_stamp, saving tuning history and deploy yaml.
  
```
### For 4 `calib_dataloader`, `val_dataloaders` and `datamodule`
- ` quantization_aware_training`: the same to `trianer.fit(train_dataloaders, val_dataloaders, datamodule)`. You don't need to specify all 3. 
- 'post_training': `calib_dataloader` is used to do calibration and `val_dataloaders` is used for evaluation to see how quantized model works. If calib/val loaders is not specified, then datamodule should be specified with `datamodule.train_loaders()` (used as `calib_dataloader`)and `datamodule.val_loaders()` not None.  In INC, evaluation is used to search for an optimal quantized model to meet users specifying tuning space.
### For 5
Is it meaning we need to support  Pytorch and Tensorflow with both INC and NNCF? Or either of INC and NNCF?
